# Generated by Django 4.2.2 on 2024-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_client_age_remove_client_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='f_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='counselor',
            name='l_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
