# Generated by Django 4.2.2 on 2024-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_quiz_resources_quizfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='media',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
