# Generated by Django 4.2.2 on 2024-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_resources_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
