# Generated by Django 4.2.2 on 2024-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_resources_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
