# Generated by Django 4.2.2 on 2024-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_resources_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
