# Generated by Django 4.2.2 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='reason',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
