# Generated by Django 4.2.2 on 2024-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_appointments_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='type',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
