# Generated by Django 4.2.2 on 2024-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appointments_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfilled',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
