# Generated by Django 4.2.2 on 2024-05-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_quizfilled_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizfilled',
            name='quiz',
        ),
    ]
