# Generated by Django 4.2.2 on 2024-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_quizfilled_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfilled',
            name='stree_value',
            field=models.FloatField(default=0),
        ),
    ]
