# Generated by Django 4.2.2 on 2024-05-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_author_blogpost_userpost_topicview_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_doctor',
        ),
    ]
