# Generated by Django 4.2.2 on 2024-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_author_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='image',
            field=models.ImageField(blank=True, default='pro_pic.png', null=True, upload_to=''),
        ),
    ]
