# Generated by Django 4.2.2 on 2024-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_counselor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='p_contact',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
