# Generated by Django 4.2.2 on 2024-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='meeting_link',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
